<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('26', '/uploads/allimg/150807/1-150PG5300X06.jpg');
$maNum = 1;
$myaddons[$maNum] = array('27', '/uploads/allimg/150807/1-150PG6195YZ.jpg');
$maNum = 2;
$myaddons[$maNum] = array('28', '/uploads/allimg/150807/1-150PGQ404634.jpg');
$maNum = 3;
$myaddons[$maNum] = array('29', '/uploads/allimg/150807/1-150PGQ42H91.jpg');
$maNum = 4;
