<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,17,1,'56KO54mH566h55CGW+WLv+WIoF0=');
$cfg_Cs[2]=array(0,18,1,'6L2u5pKt5Zu+566h55CG');
$cfg_Cs[3]=array(0,1,1,'5Liw5ae/6IO25ZuK');
$cfg_Cs[4]=array(0,1,1,'6aOO5ae/6KGl6IK+');
$cfg_Cs[5]=array(0,1,1,'5Liw5ae/576O55m9');
$cfg_Cs[6]=array(0,1,1,'5Liw5ae/5YeP6IKl6Iy2');
$cfg_Cs[7]=array(0,1,1,'5rOw5Zu95Lqn5ZOB');
$cfg_Cs[8]=array(0,1,1,'5Zyo57q/5LiL5Y2V');
$cfg_Cs[9]=array(0,1,1,'5YWo5Zu95Luj55CG5oub5ZWG');
$cfg_Cs[10]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[11]=array(0,1,1,'6LWE6K6v5Lit5b+D');
$cfg_Cs[12]=array(11,1,1,'5Lqn5ZOB5ZKo6K+i');
$cfg_Cs[13]=array(11,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[14]=array(11,1,1,'5YWs5Y+45Yqo5oCB');
?>