<?php
$z[0]=Array("cp","\r\n",1,288);
$z[0][4]['itemname']="选择产品";
$z[0][4]['autofield']="1";
$z[0][4]['type']="radio";
$z[0][4]['isnull']="true";
$z[0][4]['default']="风姿丰胸X盒 特惠价2888元,风姿补肾X盒 特惠价2888元,丰姿美白X盒 特惠价2888元,丰姿减肥茶X盒 特惠价2888元,泰国产品2盒 2000元";
$z[0][4]['maxlength']="250";
$z[0][4]['page']="";
$z[1]=Array("fukuan","\r\n",291,449);
$z[1][4]['itemname']="付款方式";
$z[1][4]['autofield']="1";
$z[1][4]['type']="select";
$z[1][4]['isnull']="true";
$z[1][4]['default']="货到付款,在线支付";
$z[1][4]['maxlength']="250";
$z[1][4]['page']="";
$z[2]=Array("xingming","\r\n",452,587);
$z[2][4]['itemname']="您的姓名";
$z[2][4]['autofield']="1";
$z[2][4]['type']="text";
$z[2][4]['isnull']="true";
$z[2][4]['default']="";
$z[2][4]['maxlength']="250";
$z[2][4]['page']="";

?>