
<field:cp itemname="选择产品" autofield="1" type="radio" isnull="true" default="风姿丰胸X盒 特惠价2888元,风姿补肾X盒 特惠价2888元,丰姿美白X盒 特惠价2888元,丰姿减肥茶X盒 特惠价2888元,泰国产品2盒 2000元"  maxlength="250" page="">
</field:cp>

<field:fukuan itemname="付款方式" autofield="1" type="select" isnull="true" default="货到付款,在线支付"  maxlength="250" page="">
</field:fukuan>

<field:xingming itemname="您的姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xingming>

<field:dianhua itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dianhua>
