<?php
$z[0]=Array("global","\$a=\"margin-right:0px;\"; \$b=\"\";if (@me==3) @me=\$a; else @me=\$b;",29,146);
$z[0][4]['name']="itemindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("field","",198,220);
$z[1][4]['name']="typename";
$z[2]=Array("field","",258,279);
$z[2][4]['name']="typedir";
$z[3]=Array("arclist","\r\n<div class=\"index_list_article_div\" >\r\n		 <div class=\"index_list_article_l\"><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title function=\"cn_substr(@me,40)\"/]</a></div>\r\n		 <div class=\"index_list_article_r\">[field:stime/]</div>\r\n  </div>\r\n",411,785);
$z[3][4]['typeid']="";
$z[3][4]['att']="";
$z[3][4]['limit']="0,10";
$z[3][4]['titlelen']="120";
$z[3][4]['infolen']="";
$z[3][4]['orderby']="pubdate";

?>