<?php
$z[0]=Array("sql","[field:content/]",51,139);
$z[0][4]['sql']="Select * from dede_addon_suipian where aid=1";
$z[1]=Array("sql","[field:content/]",175,263);
$z[1][4]['sql']="Select * from dede_addon_suipian where aid=4";
$z[2]=Array("channel","\r\n<div class=\"nav\" style=\"[field:global runphp='yes' name=autoindex]\$a=\"padding-right:0px;\"; \$b=\"\";if (@me==7) @me=\$a; else @me=\$b;[/field:global]\r\n\"><a href=\"[field:typelink /]\" target=\"_self\">[field:typename/]</a></div>\r\n",437,708);
$z[2][4]['type']="top";
$z[2][4]['row']="8";

?>