
<field:cp itemname="选择产品" autofield="1" type="radio" isnull="true" default="本类产品套餐一888元,本类产品套餐二1888元,本类产品套餐三2888元,本类产品套餐四3888元"  maxlength="250" page="">
</field:cp>

<field:fukuan itemname="付款方式" autofield="1" type="radio" isnull="true" default="货到付款,在线支付"  maxlength="250" page="">
</field:fukuan>

<field:xingming itemname="您的姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xingming>
